theme: jekyll-theme-slate
# for info: https://github.com/pages-themes/slate

markdown: kramdown

# Used by Jekyll SEO Tag
title: IBSimu Client
description: Client for the IBSimu Ion Beam Simulator library for plasma physics
# name: IBSimu Client
# tagline: Client for the IBSimu Ion Beam Simulator library for plasma physics

url: https://dgasparri.github.io/IBSimu_Client
#  email: 
author:
  name: Duccio Marco Gasparri
  github: dgasparri



show_downloads: true

github:
  owner_name: Duccio Gasparri (dgasparri)


# Site variables
# full_url: https://dgasparri.github.io/IBSimu_Client
# feed_url: feed.xml






# incremental: false
highlighter: rouge
# gist:
#   noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge